spring:
  application:
    name: notification-manager
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/notification_manager_db
    username: notification_manager
    password: notification_manager
  liquibase:
    change-log: classpath:/db/changelog/master.xml
