spring:
  application:
    name: notification-manager
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/notification_manager_db
    username: notification_manager
    password: notification_manager
  jpa:
    properties:
      hibernate:
        show_sql: false
  liquibase:
    change-log: classpath:/db/changelog/master.xml

logging:
  level:
    root: info
    org.hibernate:
      SQL: debug
      type.descriptor.sql.BasicBinder: warn

integrations:
  kafka:
    cluster:
      addresses: "localhost:9092,localhost:9093,localhost:9094"
    telegram:
      send:
        topic: "send.telegram.notification"

scheduler:
  notifications:
    timestamp:
      scheduledSendTimeMs: 60000
